### ISSUE TITLE
writeExif() creates duplicate photos in the iOS Photo Library

### ISSUE THREAD

**Issue by kueda** [inaturalist/react-native-exif-reader#5]
To replicate in iOS,

1. Adjust the example app so it writes the `UserComment` EXIF tag
1. Open the example app
1. Tap the "Take photo" button
1. Save the photo
1. Open the Photos app
1. Two copies of your photo appear, only one of which has the `UserComment` EXIF tag

Expectation: `writeExif()` should not create a duplicate photo in the Photo Library. Ideally it should update an existing photo in the Photo Library.

Maybe this involevs https://developer.apple.com/documentation/photokit/phassetchangerequest instead of `PHAssetCreationRequest` like we're currently doing.

If we cannot do this, I think we need to abandon writing EXIF to the Photo Library in iOS and maybe rename this `writeExifToFile`, or throw an error when the client passes in a URI beginning with `ph://`. This would also mean we need to adjust when we write exif in iNaturalistReactNative, e.g. at the time of capture and before we write to the CameraRoll.

**Comment by budowski** [comment]
Looked into this - the problem is that `PHAssetChangeRequest` only allows editing very specific properties of the `PHAsset` - creationDate, location (which internally gets saved as EXIF), isFavorite, isHidden. 
You cannot write any arbitrary EXIF, since that requires modifying the `PHAsset`'s data, and this can only be done by creating a new `PHAsset`.
So that's why we have a separation of two functions - one is to `writeLocation`, which works the same on both Android and iOS, and another `writeExif`, which writes a duplicate file on iOS.
For [iNaturalistReactNative](https://github.com/inaturalist/iNaturalistReactNative), we currently only write location data, so I made a [PR](https://github.com/inaturalist/iNaturalistReactNative/pull/1268) to use this latest `react-native-exif-reader` library version and use the `writeLocation` function instead.
As for the `writeExif` function, I think we should probably rename it to something like `writeExifIntoNewFile` or similar, and have it *always* copy the EXIF into a new file (also on Android) - @kueda , what do you think?

**Comment by kueda** [comment]
@budowski, is it possible to write arbitrary EXIF to an existing file that the app has access to, e.g. in its Documents directory? If so, I think I'd like `writeExif` to write arbitrary metadata to existing files on both iOS and Android (and it would *not* work for URIs referencing PHAssets in iOS, should raise an error in that case), and then the separate `writeLocation` method would write to an existing file OR an existing PHAsset.
